apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  message: "ITMO Kubernetes server's there for you :)"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        env:
        - name: MESSAGE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: message
---
apiVersion: v1
kind: Service
metadata:
  name: local-app-service
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80

